FROM openjdk:8u212-jre-alpine
EXPOSE 8080
WORKDIR /opt
VOLUME /tmp
COPY target/release-exec/spiritual-domain-example-mvc-jar-exec.jar /opt/spiritual-domain-example-mvc-jar-exec.jar
RUN sh -c 'touch /opt/spiritual-domain-example-mvc-jar-exec.jar' && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
ENTRYPOINT exec java -jar /opt/spiritual-domain-example-mvc-jar-exec.jar > /tmp/catalina.out 2>&1
